import type { Metadata, Viewport } from "next"
import { Outfit } from "next/font/google"
import { Lora } from "next/font/google"
import "./globals.css"
import { AuthProvider } from "@/components/providers/AuthProvider"
import { Header } from "@/components/layout/Header"
import { Footer } from "@/components/layout/Footer"
import { MobileFloatingCta } from "@/components/ui/MobileFloatingCta"
import { WhatsAppButton } from "@/components/ui/WhatsAppButton"
import { BackToTop } from "@/components/ui/BackToTop"
import { CookieConsent } from "@/components/ui/CookieConsent"
import { ScrollProgress } from "@/components/ui/ScrollProgress"
import { GoogleAnalytics } from "@/components/seo/GoogleAnalytics"
import { LocalBusinessJsonLd } from "@/components/seo/LocalBusinessJsonLd"
import { WebVitals } from "@/components/ui/WebVitals"
import { ToastProvider } from "@/components/ui/Toast"
import { ServiceWorkerRegistration } from "@/components/pwa/ServiceWorkerRegistration"
import { SITE_URL } from "@/lib/env"

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-outfit",
  display: "swap",
  preload: true,
  adjustFontFallback: true,
})

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-lora",
  display: "swap",
  // Secondary font — don't preload to keep the critical path focused on Outfit.
  preload: false,
  adjustFontFallback: true,
})

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#3e7787",
}

export const metadata: Metadata = {
  title: {
    default: "Mon Pilates — Studio à Larmor-Plage, Bretagne",
    template: "%s | Mon Pilates",
  },
  description:
    "Studio de Pilates face à l'océan à Larmor-Plage (Lorient). Cours tapis (doux, classique, avancé), cours privés sur appareil et Pilates pré & post-natal. Groupes tapis de 5 personnes max. Cours d'essai à 10\u20ac. Réservez en ligne.",
  metadataBase: new URL(SITE_URL),
  icons: {
    icon: [
      { url: "/favicon.svg", type: "image/svg+xml" },
    ],
  },
  // Manifest is generated by src/app/manifest.ts — Next.js 16 auto-injects
  // the <link rel="manifest"> tag pointing at /manifest.webmanifest.
  other: {
    "mobile-web-app-capable": "yes",
    "apple-mobile-web-app-status-bar-style": "default",
    "format-detection": "telephone=no",
  },
  openGraph: {
    type: "website",
    locale: "fr_FR",
    siteName: "Mon Pilates",
    url: SITE_URL,
    images: [
      {
        url: "/images/studio-reformer-ocean.webp",
        width: 1920,
        height: 1080,
        alt: "Studio Pilates Mon Pilates face \u00e0 l'oc\u00e9an \u00e0 Larmor-Plage",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Mon Pilates \u2014 Studio \u00e0 Larmor-Plage, Bretagne",
    description:
      "Studio de Pilates \u00e0 Larmor-Plage. Cours tapis, cours priv\u00e9s sur appareil, pr\u00e9 & post-natal. R\u00e9servez en ligne.",
    images: ["/images/studio-reformer-ocean.webp"],
  },
  keywords: [
    "pilates larmor-plage", "pilates lorient", "studio pilates bretagne",
    "cours pilates tapis", "pilates pré-natal", "pilates post-natal",
    "cours privé pilates", "reformer larmor-plage",
    "cours pilates morbihan", "mon pilates",
  ],
  robots: {
    index: true,
    follow: true,
  },
  alternates: {
    canonical: SITE_URL,
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr" className={`${outfit.variable} ${lora.variable}`} suppressHydrationWarning>
      <head>
        {/* No-FOUC theme bootstrap — must run before paint.
            Reads "mp-theme" (light|dark|system|null) and applies the
            matching class to <html>. With no class, the
            @media (prefers-color-scheme: dark) fallback in globals.css
            handles the system preference automatically. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem("mp-theme");var d=document.documentElement;if(t==="dark"){d.classList.add("dark")}else if(t==="light"){d.classList.add("light")}}catch(e){}})()`,
          }}
        />
        <GoogleAnalytics />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        {/* Preconnect to Google Maps: the homepage embeds a Maps iframe near the bottom
            and opening the TCP/TLS handshake early avoids a late third-party stall. */}
        <link rel="preconnect" href="https://maps.googleapis.com" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="https://js.stripe.com" />
        <link rel="dns-prefetch" href="https://www.googletagmanager.com" />
        <link rel="dns-prefetch" href="https://www.google.com" />
      </head>
      <body className="min-h-screen flex flex-col bg-mp-white text-mp-text font-body antialiased">
        <noscript>
          <div style={{ background: "#6b9fad", color: "white", padding: "12px 24px", textAlign: "center", fontSize: "14px", fontFamily: "sans-serif" }}>
            Ce site fonctionne mieux avec JavaScript activé. Veuillez l&apos;activer pour profiter de toutes les fonctionnalités (réservation, navigation, formulaires).
          </div>
        </noscript>
        <a
          href="#main-content"
          className="absolute left-4 top-0 -translate-y-full focus:translate-y-4 z-[100] px-6 py-3 rounded-xl bg-mp-ocean text-white font-heading font-semibold text-sm shadow-xl focus:outline-none transition-transform"
        >
          Aller au contenu principal
        </a>
        <ScrollProgress />
        <LocalBusinessJsonLd />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "WebSite",
            name: "Mon Pilates",
            url: SITE_URL,
            inLanguage: "fr-FR",
            description: "Studio de Pilates face à l'océan à Larmor-Plage. Cours tapis, cours privés sur appareil et Pilates pré & post-natal.",
            publisher: {
              "@type": "Organization",
              name: "Mon Pilates",
              url: SITE_URL,
              logo: { "@type": "ImageObject", url: `${SITE_URL}/logo.webp` },
            },
            potentialAction: {
              "@type": "SearchAction",
              target: `${SITE_URL}/blog?q={search_term_string}`,
              "query-input": "required name=search_term_string",
            },
          }) }}
        />
        <AuthProvider>
          <ToastProvider>
            <Header />
            <main id="main-content" role="main" className="flex-1">
              {children}
            </main>
            <Footer />
            <MobileFloatingCta />
            <WhatsAppButton />
            <BackToTop />
          </ToastProvider>
        </AuthProvider>
        <CookieConsent />
        <WebVitals />
        <ServiceWorkerRegistration />
      </body>
    </html>
  )
}
