import type { Metadata, Viewport } from "next"
import { Outfit } from "next/font/google"
import { Lora } from "next/font/google"
import "./globals.css"
import { AuthProvider } from "@/components/providers/AuthProvider"
import { Header } from "@/components/layout/Header"
import { Footer } from "@/components/layout/Footer"
import { MobileFloatingCta } from "@/components/ui/MobileFloatingCta"
import { WhatsAppButton } from "@/components/ui/WhatsAppButton"
import { BackToTop } from "@/components/ui/BackToTop"
import { CookieConsent } from "@/components/ui/CookieConsent"
import { ScrollProgress } from "@/components/ui/ScrollProgress"
import { GoogleAnalytics } from "@/components/seo/GoogleAnalytics"
import { WebVitals } from "@/components/ui/WebVitals"
import { ToastProvider } from "@/components/ui/Toast"
import { ServiceWorkerRegistration } from "@/components/pwa/ServiceWorkerRegistration"
import { SITE_URL } from "@/lib/env"

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-outfit",
  display: "swap",
  preload: true,
  adjustFontFallback: true,
})

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-lora",
  display: "swap",
  // Secondary font — don't preload to keep the critical path focused on Outfit.
  preload: false,
  adjustFontFallback: true,
})

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#3e7787",
}

export const metadata: Metadata = {
  title: {
    default: "Mon Pilates — Studio à Larmor-Plage, Bretagne",
    template: "%s | Mon Pilates",
  },
  description:
    "Studio de Pilates face à l'océan à Larmor-Plage (Lorient). Cours tapis (doux, classique, avancé), cours privés sur appareil et Pilates pré & post-natal. Groupes tapis de 5 personnes max. Cours d'essai à 10\u20ac. Réservez en ligne.",
  metadataBase: new URL(SITE_URL),
  icons: {
    icon: [
      { url: "/favicon.svg", type: "image/svg+xml" },
    ],
  },
  // Manifest is generated by src/app/manifest.ts — Next.js 16 auto-injects
  // the <link rel="manifest"> tag pointing at /manifest.webmanifest.
  other: {
    "mobile-web-app-capable": "yes",
    "apple-mobile-web-app-status-bar-style": "default",
    "format-detection": "telephone=no",
  },
  openGraph: {
    type: "website",
    locale: "fr_FR",
    siteName: "Mon Pilates",
    url: SITE_URL,
    images: [
      {
        url: "/images/studio-reformer-ocean.webp",
        width: 1920,
        height: 1080,
        alt: "Studio Pilates Mon Pilates face \u00e0 l'oc\u00e9an \u00e0 Larmor-Plage",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Mon Pilates \u2014 Studio \u00e0 Larmor-Plage, Bretagne",
    description:
      "Studio de Pilates \u00e0 Larmor-Plage. Cours tapis, cours priv\u00e9s sur appareil, pr\u00e9 & post-natal. R\u00e9servez en ligne.",
    images: ["/images/studio-reformer-ocean.webp"],
  },
  keywords: [
    "pilates larmor-plage", "pilates lorient", "studio pilates bretagne",
    "cours pilates tapis", "pilates pré-natal", "pilates post-natal",
    "cours privé pilates", "reformer larmor-plage",
    "cours pilates morbihan", "mon pilates",
  ],
  robots: {
    index: true,
    follow: true,
  },
  alternates: {
    canonical: SITE_URL,
  },
}

const jsonLd = {
  "@context": "https://schema.org",
  "@type": ["SportsActivityLocation", "LocalBusiness", "HealthClub"],
  name: "Mon Pilates",
  description:
    "Studio de Pilates \u00e0 Larmor-Plage, Bretagne. Cours tapis (doux, classique, avanc\u00e9), cours priv\u00e9s sur appareil et Pilates pr\u00e9 & post-natal face \u00e0 l'oc\u00e9an.",
  url: SITE_URL,
  telephone: "+33699183216",
  email: "contact@mon-pilates.bzh",
  image: `${SITE_URL}/images/studio-reformer-ocean.webp`,
  priceRange: "\u20ac\u20ac",
  currenciesAccepted: "EUR",
  paymentAccepted: "Cash, Credit Card",
  areaServed: [
    { "@type": "City", name: "Larmor-Plage" },
    { "@type": "City", name: "Lorient" },
    { "@type": "AdministrativeArea", name: "Morbihan" },
  ],
  address: {
    "@type": "PostalAddress",
    streetAddress: "14 Boulevard des Dunes",
    addressLocality: "Larmor-Plage",
    postalCode: "56260",
    addressRegion: "Bretagne",
    addressCountry: "FR",
  },
  geo: {
    "@type": "GeoCoordinates",
    latitude: 47.7086,
    longitude: -3.3839,
  },
  openingHoursSpecification: [
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
      opens: "09:00",
      closes: "20:00",
    },
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: "Saturday",
      opens: "09:00",
      closes: "14:00",
    },
  ],
  hasMap:
    "https://www.google.com/maps/search/?api=1&query=Mon+Pilates+Larmor-Plage",
  potentialAction: {
    "@type": "ReserveAction",
    target: `${SITE_URL}/planning`,
    name: "Réserver un cours de Pilates",
  },
  sameAs: [
    "https://www.instagram.com/monpilates.bzh",
    "https://www.facebook.com/MonPilatesBZH",
  ],
  founder: {
    "@type": "Person",
    name: "Violette Derumigny",
    jobTitle: "Instructrice certifiée Pilates",
    hasCredential: {
      "@type": "EducationalOccupationalCredential",
      credentialCategory: "certification",
      name: "FPMP — Fédération des Professionnels de la Méthode Pilates",
    },
  },
  knowsAbout: [
    "Pilates classique — Tapis",
    "Pilates doux — Tapis",
    "Pilates avancé — Tapis",
    "Cours privé sur appareil",
    "Pilates pré & post-natal",
    "Posture",
    "Rééducation posturale",
  ],
  slogan: "Le Pilates face à l'océan, à Larmor-Plage.",
  availableLanguage: ["fr", "fr-FR"],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr" className={`${outfit.variable} ${lora.variable}`} suppressHydrationWarning>
      <head>
        {/* No-FOUC theme bootstrap — must run before paint.
            Reads "mp-theme" (light|dark|system|null) and applies the
            matching class to <html>. With no class, the
            @media (prefers-color-scheme: dark) fallback in globals.css
            handles the system preference automatically. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem("mp-theme");var d=document.documentElement;if(t==="dark"){d.classList.add("dark")}else if(t==="light"){d.classList.add("light")}}catch(e){}})()`,
          }}
        />
        <GoogleAnalytics />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        {/* Preconnect to Google Maps: the homepage embeds a Maps iframe near the bottom
            and opening the TCP/TLS handshake early avoids a late third-party stall. */}
        <link rel="preconnect" href="https://maps.googleapis.com" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="https://js.stripe.com" />
        <link rel="dns-prefetch" href="https://www.googletagmanager.com" />
        <link rel="dns-prefetch" href="https://www.google.com" />
      </head>
      <body className="min-h-screen flex flex-col bg-mp-white text-mp-text font-body antialiased">
        <noscript>
          <div style={{ background: "#6b9fad", color: "white", padding: "12px 24px", textAlign: "center", fontSize: "14px", fontFamily: "sans-serif" }}>
            Ce site fonctionne mieux avec JavaScript activé. Veuillez l&apos;activer pour profiter de toutes les fonctionnalités (réservation, navigation, formulaires).
          </div>
        </noscript>
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-[100] focus:px-6 focus:py-3 focus:rounded-xl focus:bg-mp-ocean focus:text-white focus:font-heading focus:font-semibold focus:text-sm focus:shadow-xl focus:outline-none"
        >
          Aller au contenu principal
        </a>
        <ScrollProgress />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "WebSite",
            name: "Mon Pilates",
            url: SITE_URL,
            inLanguage: "fr-FR",
            description: "Studio de Pilates face à l'océan à Larmor-Plage. Cours tapis, cours privés sur appareil et Pilates pré & post-natal.",
            publisher: {
              "@type": "Organization",
              name: "Mon Pilates",
              url: SITE_URL,
              logo: { "@type": "ImageObject", url: `${SITE_URL}/logo.webp` },
            },
          }) }}
        />
        <AuthProvider>
          <ToastProvider>
            <Header />
            <main id="main-content" role="main" className="flex-1">
              <div id="main">{children}</div>
            </main>
            <Footer />
            <MobileFloatingCta />
            <WhatsAppButton />
            <BackToTop />
          </ToastProvider>
        </AuthProvider>
        <CookieConsent />
        <WebVitals />
        <ServiceWorkerRegistration />
      </body>
    </html>
  )
}
